import env from '@/env-loader';

export const config = {
  CLERK_PUBLISHABLE_KEY: env('NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY'),
  CLERK_SECRET_KEY: env('CLERK_SECRET_KEY'),

  CLERK_SIGN_IN_URL: env('NEXT_PUBLIC_CLERK_SIGN_IN_URL'),
  CLERK_SIGN_UP_URL: env('NEXT_PUBLIC_CLERK_SIGN_UP_URL'),
  CLERK_AFTER_SIGN_IN_URL: env('NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL'),
  CLERK_AFTER_SIGN_UP_URL: env('NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL'),

  CLERK_AFTER_SIGN_OUT_URL: '/',

  CLERK_WEBHOOK_SECRET: env('CLERK_WEBHOOK_SECRET'),

  PUBLIC_ROUTES: ['/', '/api/webhooks(.*)', '/api/uploadthing'],

  LIVEKIT_WEBSOCKET_URL: env('LIVEKIT_WEBSOCKET_URL'),
  LIVEKIT_API_URL: env('LIVEKIT_API_URL'),
  LIVEKIT_API_KEY: env('LIVEKIT_API_KEY'),
  LIVEKIT_API_SECRET: env('LIVEKIT_API_SECRET'),

  UPLOADTHING_SECRET: env('UPLOADTHING_SECRET'),
  UPLOADTHING_APP_ID: env('UPLOADTHING_APP_ID'),
};
