const ENV = {
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY',
  CLERK_SECRET_KEY: 'CLERK_SECRET_KEY',

  NEXT_PUBLIC_CLERK_SIGN_IN_URL: 'NEXT_PUBLIC_CLERK_SIGN_IN_URL',
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: 'NEXT_PUBLIC_CLERK_SIGN_UP_URL',
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: 'NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL',
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: 'NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL',
} as const;

type EnvironmentVariable = typeof ENV;

export default function env(key: keyof EnvironmentVariable) {
  return ENV[key];
}
